# Generated by Django 5.2.6 on 2025-09-21 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departamento', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aniomes', models.CharField(max_length=6)),
                ('tot_ing', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tot_des', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('neto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='NominaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bono', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tot_ing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iess', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prestamo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tot_des', models.DecimalField(decimal_places=2, max_digits=10)),
                ('neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.empleado')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.nomina')),
            ],
        ),
    ]
