# Generated by Django 5.2.6 on 2025-09-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominadetalle',
            name='iess',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nominadetalle',
            name='neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nominadetalle',
            name='tot_des',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nominadetalle',
            name='tot_ing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
